name: Hello World
on: [push, pull_request]
jobs:
  build:
      name: hello world build
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run echo
        run: |
          echo "Hello World"
        shell: cmd
