name: MSBuild
on:
  push:
    branches:
      - msbuild-test
jobs:
  build:
    name: MSBuild
    # runs-on: self-hosted
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # - name: Setup MSBuild.exe if not exist msbuild command
    #   uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      env:
        MSBUILD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
      run: $MSBUILD msbuild_actions_sample.sln -p:OutDir="out"
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: ./msbuild_actions_sample/out/

